Add support for Lutris library WoW installation detection on Linux
WowUp/WowUp pull request #1054
Opened 2021-11-13 05:22 UTC by fultonm

Hello, and thanks for this wonderful addon manager!

My apology in advance for coming out of no where with an implementation. This is just something that worked for me and I wanted to share it. I'm happy to improve and maintain this feature in the future as well if you like it.

This provides an implementation for Linux addon directory discovery process.

The most frictionless way for Linux gamers to install non-Steam games is with the Lutris Library: https://lutris.net/](https://lutris.net/) and quite often we will use this platform instead of installing manually with Wine, as they maintain various settings and configuration to make it "just work".

The Library has a known configuration file in the user's home directory under `~/.config/lutris/system.yml` and we can follow the location configured for `game_path` to find possible Warcraft directories. Lutris currently has 3 entries for installing WoW, but all of them are exactly the same Battle.net launchers as far as directory structure goes. This just checks each one and runs with the first valid WoW path it finds.

In a few areas outside of the `warcraft.service.linux.ts` it was necessary to add an if statement to make it work because the root C:\ drive was configured as the installation path instead of using the blizzardAgentPath which contains the Lutris library directory prefix in Linux.

I'm happy to improve this as I probably missed something related to following the architecture so please let me know your feedback!

2021-11-13 11:00 UTC, linaori reviewed
As I personally have never used Lutris I've asked a friend, and they've confirmed that the product.db was indeed in a path that would be found in this code:
```
/home/<username>/Games/world-of-warcraft/drive_c/ProgramData/Battle.net/Agent/product.db
```

2021-11-13 16:35 UTC, fultonm commented
90% of the time that's going to be the case because the default installation path is `~/<user>/Games/`, but it is configurable as a Lutris preference in `system.yml` if they want to move their folder to an external hard drive or not clutter the home folder.
However, I just checked a default configuration from installing Lutris for the first time and `system.yml` does not exist at least until a different library location is selected. So I'll update this to default to `~/<user>/Games/` if `~/.config/lutris` exists but the system file doesn't exist, or `game_path` is not present within the file.

2021-11-14 03:52 UTC, fultonm commented
Ok, this should work better.

2021-11-14 06:17 UTC, jliddev requested changes
Looks fine overall, just some minor code shuffling changes.

2021-11-14 06:17 UTC, jliddev commented on wowup-electron/src/app/services/warcraft/warcraft-installation.service.ts
> +  private getFullLutrisProductPath(location: string, agentPath: string, clientType: WowClientType): string {
See above linux comment.

Adding a platform specific step to "getInstalledProducts", after 'decodedProducts' is called might be a decent way to move this?
(IE: this._impl.resolveProducts(decodedProducts) or something)

2021-11-14 06:17 UTC, jliddev commented on wowup-electron/src/app/services/warcraft/warcraft-installation.service.ts
> +    if (this._electronService.isLinux) {
See above linux comment

2021-11-16 13:47 UTC, fultonm commented
Sounds good and I definitely agree with those points. I should be able to explore these later this week.

2021-11-20 22:19 UTC, fultonm commented
Sorry for the delay, I was doing job interviews and playing SoM this week 🤭

I think the `resolveProducts` solution was a pretty smooth way to do that. Let me know how this looks to you.

2021-11-23 14:59 UTC, jliddev commented
I just did a merge of dev into your branch, should be conflict free.

2021-12-27 16:09 UTC, jliddev commented
Are we cancelling this? seemed like it was almost done?

2021-12-30 18:41 UTC, fultonm commented
Sorry, I was confused about what I did with the rebase. I was working on cleaning up the commits so my PR didn't include unrelated changes (40 files changed), but I see this PR now correctly shows the right amount of changes.

2022-01-18 04:41 UTC, jliddev approved these changes

2022-01-18 04:41 UTC, merged