Update pt.json
WowUp/WowUp pull request #564
Opened 2020-12-02 14:05 UTC by danielschmitz

Update "scan addon" terms

2020-12-02 15:09 UTC, dogo requested changes

2020-12-02 15:09 UTC, dogo commented on wowup-electron/src/assets/i18n/pt.json
> +      "ADDON_SCAN_STARTED": "Scan de addons iniciado...",
@danielschmitz Porque você usa `Scan` aqui, mas traduz embaixo `Escaneando`, acho que seria legal a ter um padrão e deixar tudo em pt-br, tipo:
```
Escaneamento de addons completo...
Escaneamento de addons iniciado...
Escaneando {count} pastas...
```

2020-12-02 15:57 UTC, danielschmitz commented on wowup-electron/src/assets/i18n/pt.json
> +      "ADDON_SCAN_STARTED": "Scan de addons iniciado...",
Pode ser!

2020-12-02 18:32 UTC, dogo approved these changes

2020-12-10 07:39 UTC, jliddev approved these changes

2020-12-10 07:39 UTC, merged